name: 'Docker: build and push'

on:
  push:
    branches:
      - main
    paths: 
      - 'service_a/**'
      - 'service_b/**'

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [service_a, service_b]  # List your services here

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Convert repository owner to lowercase and set as env var
        run: echo "LOWERCASE_REPOSITORY_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: ghcr.io/${{ env.LOWERCASE_REPOSITORY_OWNER }}/${{ matrix.service }}:latest
