name: 'Terraform: Apply'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.4

      - name: 'Azure Login'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Terraform Init'
        run: terraform init
        working-directory: ./Infra

      - name: 'Terraform Plan'
        run: terraform plan
        working-directory: ./Infra

      # - name: 'Terraform Apply'
      #   run: terraform apply -auto-approve
      #  working-directory: ./Infra
