name: 'Terraform: Apply'

on:
  push:
    branches:
      - main
    paths: 
      - 'Infra/**'
  schedule:
    - cron: "20 0 * * 0"  # This cron expression triggers the workflow every Sunday at midnight + 20 mins to update the ssh key being rotated.

  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      WORKING_DIRECTORY: './Infra' 

    # Default settings for all `run` commands in this job
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.4
     
      - name: 'Azure Login'
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'

      - name: 'Terraform Init'
        run: terraform init 

      - name: 'Terraform Plan'
        run: terraform plan -no-color

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve -no-color
