name: Publish Multiple Docker Images to GitHub Container Registry

on:
  push:
    branches:
      - main  # Adjust this as necessary
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - image_tag: servicea
          dockerfile_path: ./ServiceA/Dockerfile
        - image_tag: serviceb
          dockerfile_path: ./ServiceB/Dockerfile
    env:
      LOWERCASE_REPOSITORY_OWNER: ${{ github.repository_owner }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Convert repository owner to lowercase
        run: echo "LOWERCASE_REPOSITORY_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.dockerfile_path }}
          push: true
          tags: ghcr.io/${{ env.LOWERCASE_REPOSITORY_OWNER }}/example-microservice:${{ matrix.image_tag }}
