name: Publish Multiple Docker Images to GitHub Container Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [servicea, serviceb]  # List your services here

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Convert repository owner to lowercase and set as env var
        run: echo "LOWERCASE_REPOSITORY_OWNER=${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]'" >> $GITHUB_ENV
        shell: bash

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: ghcr.io/${{ env.LOWERCASE_REPOSITORY_OWNER }}/example-microservice:${{ matrix.service }}
