name: Publish Multiple Docker Images to GitHub Container Registry

on:
  push:
    branches:
      - main  # Adjust this as necessary
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image_tag: servicea
            dockerfile_path: ./ServiceA
          - image_tag: serviceb
            dockerfile_path: ./ServiceB

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.dockerfile_path }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/example-microservice:${{ matrix.image_tag }}
