name: 'Kubectl: Apply'

on:
  push:
    branches:
      - main
    paths: 
      - 'kubernetes_IAC/**'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    env:
      WORKING_DIRECTORY: './kubernetes_IAC' 

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch kubeconfig from Azure Key Vault
        run: |
          az keyvault secret show --name ${{ secrets.kubeconfigSecretName }} --vault-name ${{ secrets.KVName }} --query value -o tsv > kubeconfig
          echo "KUBECONFIG_FILE=kubeconfig" >> $GITHUB_ENV

      - name: Deploy to Kubernetes
        run: |
          for file in $WORKING_DIRECTORY/*.yml; do
            kubectl apply -f "$file"
          done
        env:
          KUBECONFIG: ${{ env.KUBECONFIG_FILE }}
