name: 'Kubectl: Apply'

on:
  push:
    branches:
      - main
    paths: 
      - 'kubernetes_IAC/**'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    env:
      WORKING_DIRECTORY: './kubernetes_IAC' 

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Install kubectl
      #   run: |
      #     curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
      #     chmod +x ./kubectl
      #     sudo mv ./kubectl /usr/local/bin/kubectl

      # # Add the Azure CLI installation step here
      # - name: Install Azure CLI
      #   run: |
      #     curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Fetch kubeconfig from Azure Key Vault
        run: |
          az keyvault secret show --name ${{ secrets.kubeconfigSecretName }} --vault-name ${{ secrets.KVName }} --query value -o tsv > kubeconfig
          echo "KUBECONFIG_FILE=kubeconfig" >> $GITHUB_ENV

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./$WORKING_DIRECTORY/*
        env:
          KUBECONFIG: ${{ env.KUBECONFIG_FILE }}
