name: Generate and Push SSH Key to Azure Key Vault

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"  # This cron expression triggers the workflow every Sunday at midnight

jobs:
  generate-and-push-ssh-key:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ secrets.ARM_CLIENT_ID }}",
              "clientSecret": "${{ secrets.ARM_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.ARM_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.ARM_TENANT_ID }}"
            }

      - name: Generate SSH key pair
        id: ssh-key
        run: |
          ssh-keygen -t rsa -b 4096 -f github_actions_ssh_key -N "" > /dev/null

      - name: Upload SSH private key to Azure Key Vault
        run: |
          az keyvault secret set --vault-name ${{ secrets.KVName }} --name github-ssh-private-key --file github_actions_ssh_key > /dev/null
      
      - name: Upload SSH public key to Azure Key Vault
        run: |
          az keyvault secret set --vault-name ${{ secrets.KVName }} --name github-ssh-public-key --file github_actions_ssh_key.pub > /dev/null
